parameters:
  stageName: 'verify'
  stageDisplayName: 'Build & Test'
  jobName: 'verify'
  jobDisplayName: 'Build & Test'
  dotNetVersion: '3.x'
  buildConfiguration: 'release'
  projectPath: ''

stages:
- stage: ${{ parameters.stageName }}
  displayName: ${{ parameters.stageDisplayName }}
  dependsOn: ${{ parameters.dependsOn }}
  jobs:
  - job: ${{ parameters.jobName }}
    displayName: ${{ parameters.jobDisplayName }}
    pool:
      vmImage: 'windows-latest'
    steps:
    - task: UseDotNet@2
      displayName: Install .NET Core ${{ parameters.dotNetVersion }}
      inputs:
        packageType: 'sdk'
        version: '${{ parameters.dotNetVersion }}'
    - task: DotNetCoreCLI@2
      displayName: Build ${{ parameters.projectPath }}
      inputs:
        command: 'build'
        projects: ${{ parameters.projectPath }}
        arguments: '--configuration ${{ parameters.buildConfiguration }}'
    #- task: DotNetCoreCLI@2
    #  displayName: Run Unit Tests
    #  inputs:
    #    command: 'test'
    #    projects: './src/CarWash.Tests.Unit/CarWash.Tests.Unit.csproj'
    #    arguments: '--configuration ${{ parameters.buildConfiguration }} --filter Category=Unit'